[package]
name = "payment_kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nfc1 = {version = "0.5", default-features = false }

# nfc1-sys = {version = "0.3", default-features = false }

